#!/usr/bin/env bash
docker-compose up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===================== 🚀 Done 🚀 ===================

      Created by Rafael Corrêa Gomes
      v.$version
      Access your new links:

      🌎 Web server: http://localhost:9000/
      ⚙️ PHPMyAdmin: http://localhost:9080
      ✉️ Local emails: http://localhost:9025

===================== 🚀 Done 🚀 ==================="
